### ISSUE TITLE
No module named route53

### ISSUE THREAD

**Issue by reformedot** [shivsahni/NSBrute#7]
Hi, I just installed the requierements, but error:
 File "NSBrute.py", line 1, in <module>
    import route53
ImportError: No module named route53

appear when I try to launch the script

**Comment by mardinyadegar** [comment]
Your python package manager is not working properly. Are you on Mac OS X? I had the same issue. To get around it, I use a VirtualBox Kali Linux Image from Offensive Security and was able to get it all running fine.

**Comment by reformedot** [comment]
@mardinyadegar I'm on Mac OS X. The only alternative is to use it on a Kali Linux Image?

**Comment by mardinyadegar** [comment]
That was the only alternative I could find. I apologize, I just felt this was a better work around for me since it was an environment that I could quickly set up and it would have most of the python environment set up for me too. The issue you're experiencing and so am I is that pip is not able to put the package in the right area and as such, it cannot import route53 because it cannot find it. I'd check your pip install or just go with the option I provided.

**Comment by reformedot** [comment]
Okay thanks for your response @mardinyadegar ! I will try to use Kali Linux if there are no other way.

**Comment by Monitrisha** [comment]
I am facing same issue after following all the requirements. Can anyone guide me in this?
